### ISSUE TITLE
RuntimeError: No available devices

### ISSUE THREAD

**Issue by codewithleo1103** [geaxgx/depthai_hand_tracker#25]
I installed requirements and trying run python3 demo.py. Then show:

*Palm detection blob : /home/ubuntu/Desktop/research/hand/depthai_hand_tracker/models/palm_detection_sh4.blob
Landmark blob       : /home/ubuntu/Desktop/research/hand/depthai_hand_tracker/models/hand_landmark_lite_sh4.blob
Traceback (most recent call last):
  File "./demo.py", line 59, in <module>
    tracker = HandTracker(
  File "/home/ubuntu/Desktop/research/hand/depthai_hand_tracker/HandTracker.py", line 130, in __init__
    self.device = dai.Device()
RuntimeError: No available devices*

Please help me solve this problem!!!

**Comment by DBraun** [comment]
This error is probably unrelated to the hand tracking code. One possible explanation is that your camera isn't connected correctly. Consider following the steps here (https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/) if you haven't already.
